apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-data
spec:
  capacity:
    storage:  {{ include "seafile.seafileDataVolume.storage" . }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ include "seafile.seafileDataVolume.path" . }}
